name: TestWorkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: | 
          echo "Hello, World"
          echo "Felo Adel"
      - name: checkout branch
        uses: actions/checkout@v5.0.0

      - name: list all Directory and Folders
        run: |
          pwd
          ls -R
      
